In [1]:
import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.getcwd())))
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from lightgbm import LGBMClassifier

from fmclp.run_experiment import run_experiment
from fmclp.get_data import get_data

In [2]:
loan = get_data('loan')
loan

,loan_amnt,int_rate,target,dti,revol_bal,total_pymnt,total_rec_prncp,term_ 60 months,verification_status_Source Verified,verification_status_Verified,...,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding
0,5000.0,10.65,0,27.65,13648.0,5861.071414,5000.00,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,2500.0,15.27,1,1.00,1687.0,1008.710000,456.46,True,True,False,...,False,False,False,False,False,False,False,False,False,False
2,2400.0,15.96,0,8.72,2956.0,3003.653644,2400.00,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,10000.0,13.49,0,20.00,5598.0,12226.302212,10000.00,False,True,False,...,False,False,False,False,False,True,False,False,False,False
5,5000.0,7.90,0,11.20,7963.0,5631.377753,5000.00,False,True,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887351,4200.0,15.99,1,36.93,12943.0,1026.020000,667.96,False,False,True,...,False,False,False,True,False,False,False,False,False,False
887364,10775.0,6.03,0,13.22,10776.0,11071.870000,10775.00,False,False,False,...,False,False,False,False,False,False,False,False,False,False
887366,6225.0,16.49,0,18.58,1756.0,7050.460000,6225.00,False,True,False,...,False,False,False,False,False,False,False,False,False,False
887369,4000.0,8.67,0,12.63,1700.0,4158.020000,4000.00,False,False,True,...,False,False,False,False,False,False,False,False,False,False
887371,10850.0,19.24,1,29.44,6987.0,2396.050000,1405.77,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [5]:
y = loan.drop('target', axis=1)
x = loan['target']
y_train, y_test, x_train, x_test = train_test_split(y, x)
lg = LGBMClassifier(verbose=-1)
lg.fit(y_train, x_train)
lg_preds = lg.predict(y_test)
accuracy_score(lg_preds, x_test)

0.9373389355742296

In [ ]:
experiment = run_experiment(dataset=loan,
                   number_experiments=100,
                   multiplier=20,
                   number_iterations=30, 
                   interior_classifier='rf', 
                   folder = '../../results/main_testing_results',
                   dataset_name='loan',
                   initial_classifier=LGBMClassifier(verbose=-1),
                   write_benefit=True)